apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: admin01
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0VkbTkyWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQU1oZXZNblFXbVl6djlGRWlXYmxUSlNrUkdpVVhhTzQ4eThMaGhCMUo4dmJlV0h5CkZSajI0TGs1QjVaR0FiazlhS28zeUp4TWx3VlN3Q1hxckJQN3NNTCtGWG5DdExTSkRBSUVWQ1QzcnhIWlZaV3QKc1k1NmVxOUk0QnJtbndxS1lPMURPUzhac0YvRWRQZDljSldGOTVpbFc4eDVKd1dGNnNrdXB0WFZPUndRby9RbAoyWFplUmFFbUdhZ05mdVo1RzVsOWwxa2RHenNETVpoTFArQzBTbWE4UE5HZ1Q1MmFoNmd1dzBjUkplN2lBSE1TCm0xL244cC9MOG12Qm9WS1FvSG5UM3QzK1Bib3FsUGhPcVlHaWRTV3lDb3lWdFlXUVJRSUtVb1Q2Y1lFZG1SVVoKSHhNaHBHRm15Y2dWNUJxQzNPTmowM2thM3hlaFYzcFhqNjc4TkcwQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQkFtKytTZFhHWGtOdktsTHF3UTdyWE9ucmY3WG4yUnBVeVh2eTdWMVNSMTFlUDBpekhjS0JoCnZnMmdDTDUzUEcvMXJNVzZvZzcxYjVGbC94UFJ6elR2NXZzaGxrMkFGWDFVUTErajd2YXdIUzB6NnlEbERoYjMKdnBmL3YxY29lRlVuSkxQOXNCRlFQWHFDcXlQVG04WW4rYkpTaVBmM1FqY2kzaGFwNXl5ZzkyUVBjWklybjN3YwpkWjBORlU1TmdySnFiaUwrVjk4dHpvaHRLUWJJM0lsYlMvaGFycXlpUGVrVjlmMjR2djF5RnEzRndnOHZ3bjE1CnlKcktiVUJZNUs4QkxMWktGYTZqWmNDRERVWXJibGJlbktBRldBR0xXMmIyMGxNekdESDVJejBxazFEdkZxS2oKaTdTdzBjV1c2NnVOckhGeVQyMWw5ZU01c3ZZWmJNQ1UKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
