apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: bazcorp
spec:
  limits:
  - type: Container
    default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 256Mi
      cpu: 250m
