apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
  namespace: bazcorp
spec:
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  hostPath:
    path: /k8s_local_pv
    type: Directory
