apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-rbac
  namespace: bazcorp
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["get","watch","list","create","update","delete"]
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["create"]
