apiVersion: v1
kind: Namespace
metadata:
  name: secret-tls

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-tls-deploy
  namespace: secret-tls
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secret-tls-pod
  template:
    metadata:
      labels:
        app: secret-tls-pod
    spec:
      containers:
        - name: secret-tls-cont
          image: bazdoc/go-playground:1.13
          ports:
            - name: web-port
              protocol: TCP
              containerPort: 8000
              

---

apiVersion: v1
kind: Service
metadata:
  name: secret-tls-service
  namespace: secret-tls
spec:
  type: LoadBalancer
  selector:
    app: secret-tls-pod
  ports:
    - name: web-port-service
      port: 8080
      targetPort: 8000


---

apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: secret-tls
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvVENDQW9rQ0ZIeU5uMkV4L0FoWmlnbk40czdrNjRQdStiQlVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1JR00KTVFzd0NRWURWUVFHRXdKQlFqRUxNQWtHQTFVRUNBd0NRMFF4RGpBTUJnTlZCQWNNQlVWR1gwZElNUTR3REFZRApWUVFLREFWdGVXOXlaekVTTUJBR0ExVUVDd3dKYlhsdmNtZDFibWwwTVJnd0ZnWURWUVFEREE5MGJITXVZbUY2ClkyOXljQzVqYjIweElqQWdCZ2txaGtpRzl3MEJDUUVXRTIxNVpXMWhhV3hBWlhoaGJYQnNaUzVqYjIwd0hoY04KTWpZd016SXlNRGN6TnpFM1doY05NamN3TXpJeU1EY3pOekUzV2pDQmpERUxNQWtHQTFVRUJoTUNRVUl4Q3pBSgpCZ05WQkFnTUFrTkVNUTR3REFZRFZRUUhEQVZGUmw5SFNERU9NQXdHQTFVRUNnd0ZiWGx2Y21jeEVqQVFCZ05WCkJBc01DVzE1YjNKbmRXNXBkREVZTUJZR0ExVUVBd3dQZEd4ekxtSmhlbU52Y25BdVkyOXRNU0l3SUFZSktvWkkKaHZjTkFRa0JGaE50ZVdWdFlXbHNRR1Y0WVcxd2JHVXVZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBeSt0SVplWXY3R0VrSm1lTEgxc1AzR2tqTzNXcmNaT1RBaWIwV1NuYzI0dU5pdXVnCjhCUDRHZGVKN0VVSUh5LzVIYTlqNjdRc04vRjhlK0J5VjIvc0FpejZ0UHBoeHhBc1pnT0V6YVFrQ3dHd3N2NXgKVDNncFFMTHBSOEpwUCtxVy9lVlpIUllBSVFiM0dVYm1lOHpDeTVQOGpIMUM0NDRVWE5CaFBjOHRtMXF5Tk02OQpGdjdtSGp0c3ZHcUJvTjlDbG12N0VObzR2UWk4M1RhWS96MGlPZjRmWHdUTjJzWnVPR1NhSmRHb0FTVS9LTC9WCjN1Z0Q3RE9Ta1AxSmxmWm5GRW5hTHJMRncwUVF1MWNPT3pTM3QwNmJ2Um45Tk1oWWxnRnFKVUoza0xuNWhOam4KYUxmNTg1T00zaUpnQnAxMXhSODlPdmtNUUszTHBTWlh1d0xyOFFJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFDUUNLR1BqMENhZmx3bHo0S0l4dUFJdlpNeWlkWGtlTytWc0lnWmVOUEdNVDlLc1RyMmdvMTBLNlZHCmg0bmx1YWRZOTcrZGRDT3lPQ3kvdTJDa2NNTm5STm1CMVd1ZUFYNk5NdkVYZjRiTWVWdVIzVE82U2FVZ0VueGEKeEpvNlhpZ1F3R0JsYmFSMURrbnhaM0gvWkpjQk5LdXBkUTNvSXV3UnNiOGk2bUFhQXBTNXlLTVJXaE5Xa1VWWQpNSDJEdk9yQzF4clpsZUZZei9UUjE2RWdTMmxMWHpXUWEveUFuL0FhYlZ4NHRvQTlBbDNkZmtHb1cwUk8zZi9uCmo5UUlTcUtGUVNBbDlBVGl2QmxSN1hvNGpFaDFqQkJWUTNjQVNWVC9TZGVTcDVrMytPZk9oZzFjdmMxRy9XRDEKSzJleWhLR3p2UWhwM2JIbmYyV0ZFaGJpL2JWZwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRREw2MGhsNWkvc1lTUW0KWjRzZld3L2NhU003ZGF0eGs1TUNKdlJaS2R6Ymk0Mks2NkR3RS9nWjE0bnNSUWdmTC9rZHIyUHJ0Q3czOFh4Nwo0SEpYYit3Q0xQcTArbUhIRUN4bUE0VE5wQ1FMQWJDeS9uRlBlQ2xBc3VsSHdtay82cGI5NVZrZEZnQWhCdmNaClJ1Wjd6TUxMay95TWZVTGpqaFJjMEdFOXp5MmJXckkwenIwVy91WWVPMnk4YW9HZzMwS1dhL3NRMmppOUNMemQKTnBqL1BTSTUvaDlmQk0zYXhtNDRaSm9sMGFnQkpUOG92OVhlNkFQc001S1EvVW1WOW1jVVNkb3Vzc1hEUkJDNwpWdzQ3TkxlM1RwdTlHZjAweUZpV0FXb2xRbmVRdWZtRTJPZG90L256azR6ZUltQUduWFhGSHowNitReEFyY3VsCkpsZTdBdXZ4QWdNQkFBRUNnZ0VBSTBGRnpvdzUrOW1kbU9Bczd0cGRCeVBNT2hMeGRaem9mU1pEOTRoanpUYzIKM080NDhGamJlNGhHcWFrVHF1U3Q0cUo0bVg4WWFBR2hubjhpOVpmOWl6REFsWHAyWGlhZkxuSHNTMnRWNmVzOApZKzNXcEVFbmpLNkI0MnlxcXFqQnV4cWtTZ0dNT3ltTG5meWlpNFBPcDhpcGtKWjFjb2NWWVNpTHIxWjYwWkZSCkYwNGdweXduTmlnOGIrOVg1YUdZWjVaSEtXb0lIemV1cS9YWWtqaEs2ZDY3dEJZenFpT3hJUS9mUHNBbFlFWFkKV0dMbFlmZGd0Z2JVcFdoWE1RYlNFb1NaZWtQSzJCK0V2WHNIS0NhaDJRL2xQVGUvVFE1T0VIV3dWOVVVQ3BwagpzRHRFa0VvY3JDZ015VkM5Vm9LWkFkS3JqNGJkdHZTK2hwSGxiakY5R1FLQmdRRHFlQjdyL1BXYVR2Q2NMZTBuClNaQ1FibUtIMFhZcVR1ZkVnS0hwbTNraVlWd3FlQ1hmS0hwakxURnE5QUY3bmZTQmZIVGY4SUdMZ0QwN1Z4NHkKS09qOVJiMlI3R1VJTDJiNE1JZkpEdFBLdnV5clMwRmxxVngrdUo4UlBYSmVpbGE5aFhlZFpla2FQRlhIYkx0Zwo2amNsOTc1Z0lyN3lianJrSXZkT0doQUE3UUtCZ1FEZXBQMytHaGpna25oL1UrVzZxTXJjRys4TEtpQXBNc1NOCmFRZVY2ZUxRZno5MzN4RVlzTmZOaHJLMVprUndTNU1sV2VNeE1yZmlLY3VPS0Y5dkR6SjNETzBCdkRtNFN1TjEKaWVaYnFWbWpvRWlWQkJpNWF0UEUxYzg3VHBzRUtxekxJSW1jemhIc0Rxbk9JaVIwUGtmWDdxVFVKSndzNnZ5YQphVDNxYWNtcWxRS0JnQVZOVmhXc0VMbStrejVVNDRvQjVkeitRZ2drT25IV2V2TThuV3kwOFZaUHNVL2NpNjZ5Ck1hSlFnVStUMlB5OG82elI3YXFxdTZNMThTeUlXY3gwbEdBMTFZV1pQT2VrZXNXZUExUU9tOGQzN2M0cDAzN0QKQjY1dDZscnZjc2lraERXZzhRV0VLbk5IYmdFbWVrNUV2WjZFTGEvcTJUcU9ONUsxSDdhS2JGWTVBb0dBV0dMRgpsamVFQXJzQzdRRkFaTjZYVWRRaERKeVhrZU5lbGdqSkF5R0xjbHZodFZPdnRNNlhqVGJaQVJ4dE5PczdxZ3RLCkh3RFVjUXRJak5ISU9RMmVhaGFPakM3Tjl6UjdvZkN4cTFmS2h5T2RUTk1JZ2F0QUVKY1VvcVdzOG5XQ2pVMEkKZEdCMlN2RHpSaXJWci9QOWoySmt1dmNock05SW9uLy9IVzBMcXhVQ2dZRUF2TzBZSGN4bkthalZjb3VrQzAregpnU2RjSElaRFFQWFNOaHd3clF3Rkg1RTQrSnQvTGVUZnRveGdZRXRVeHZWK3l3YVIrY2xDRDJVQzExQjIzM3drCk10ZFVWVnFXUTc4RkFOOU42YTBSa0dnbXRSU29wVGNacUJLbjluTlF3MkxZcmZQMGx1a2lBbmNtbXd0VWNmNEUKdWRjTkxQQXd3WnNaK2Q1QTBtQURTVVU9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secret-tls-ingress
  namespace: secret-tls
spec:
  ingressClassName: nginx
  rules:
    - host: tls.bazcorp.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: secret-tls-service
              port:
                number: 8000
  tls:
    - hosts:
        - tls.bazcorp.com              
      secretName: tls-secret
